### ISSUE TITLE
Insert parameters in params DSL from Map

### ISSUE THREAD

**Issue by THeK3nger** [rybalkinsd/kohttp#109]
Hi guys, this is probably more a question than a bug. Imagine I have this function:

```
    override fun get(endpoint: String, params: MutableMap<String, Any>?): Response {

        val response = httpGet {
            host = "https://url-for-my-web-service"
            path = endpoint
            param {
                "token" to token
            }
        }
        return  response;
    }
```

I need to merge the parameters I get from `params` and the `token` parameter. However I do not know how to manipulate the `param` DSL to do that. Is it possible in the current version?

**Comment by rybalkinsd** [comment]
Hi @THeK3nger , thanks for your question.

I suggest you could try this technique:

    override fun get(endpoint: String, params: MutableMap<String, Any>?): Response {

            val response = httpGet {
                host = "https://url-for-my-web-service"
                path = endpoint
                param {
                    params?.forEach { (k, v) -> 
                        k to v.toString() 
                    }
                    "token" to token
                }
            }
            return  response
        }

**Comment by rybalkinsd** [comment]
So for each entity from `params` map you will call infix `to` function from `ParamContext`.
Please let me know if it will solve your problem

**Comment by THeK3nger** [comment]
Thank you @rybalkinsd . This solution seems to work fine! :)
