### ISSUE TITLE
Boolean/Null values are not supported in json 

### ISSUE THREAD

**Issue by Centaur** [rybalkinsd/kohttp#113]
Valid json types include `String`, `Number`, `Boolean`, `Null(empty)`, `Object`, `Array`

See [the code](https://github.com/rybalkinsd/kohttp/blob/master/src/main/kotlin/io/github/rybalkinsd/kohttp/util/json.kt)

Currently `Boolean` and `Null(empty)` values are not supported.

**Comment by rybalkinsd** [comment]
@Centaur thanks for your feedback. Fix will be provided in the next version

**Comment by rybalkinsd** [comment]
#114
