### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by DeviantBadge** [rybalkinsd/kohttp#129]
Currently our documentation looks like one big class, that contains all logic. We can find it on [kohttp.gitbook.io](https://kohttp.gitbook.io/docs/).

Our target - create that documentation that will be more divided on parts, such as:
Async methods, Sync methods, Clients and so on

Add 'stars' tag on front page

**Comment by rybalkinsd** [comment]
@DeviantBadge I just added a `publications` section
