### ISSUE TITLE
Parse responses in tests with jackson

### ISSUE THREAD

**Issue by rybalkinsd** [rybalkinsd/kohttp#17]
Currently most of tests are using only response code to validate results.
The idea is to read postman-echo documentation and check what exactly do we expect in response body. Most of responses are json with 

- cookies
- headers
- etc

need to check all the expectations

**Comment by rybalkinsd** [comment]
@gokulchandra not in progress. Welcome to pick this task. Any questions about details are very welcome

**Comment by gokulchandra** [comment]
@rybalkinsd Cool. I will keep you posted on its progress. 👍

**Comment by gokulchandra** [comment]
Resolved in #60
