### ISSUE TITLE
My APP crash

### ISSUE THREAD

**Issue by Gius-8** [rybalkinsd/kohttp#181]
Hello,
I have a problem with my app when I use this library. When I make a GET request the app crashes.
I'm using this instruction:
`val response: Response = "https://google.com/search?q=iphone".httpGet()`
Any solution for me? Thank you :)

**Comment by simonenkoi** [comment]
@Gius-8 could you define an exception that results app crash? I had one while trying to convert the body to JSON and manual setting of `com.squareup.okhttp3.okhttp` dependency to 4.0.1 version helped

**Comment by rybalkinsd** [comment]
Feel free to reopen with crash report and more details of what happened
