### ISSUE TITLE
Function to in FormBodyBuilder with nullable type has unexpected behavior

### ISSUE THREAD

**Issue by MEJIOMAH17** [rybalkinsd/kohttp#206]
```kotlin 
 val paramArg= json.decodeFromString<Map<String, String>>(rs)["params"]

 val result = httpPost{
     url("https://example.com")
     body {
        form {
            "params" to paramArg
        }
     }
 }
```

This code does not append 'params' arg to form, because function [to](https://github.com/rybalkinsd/kohttp/blob/master/kohttp/src/main/kotlin/io/github/rybalkinsd/kohttp/util/form.kt#L13) works with nonnullable type. paramArg is nullable, therefore function 'to' works from standart kotlin library.

**Comment by rybalkinsd** [comment]
Hi @MEJIOMAH17 thanks for reporting this one! Could you please share how http request form should look like with null? (params=???)

**Comment by MEJIOMAH17** [comment]
@rybalkinsd I have created [PR](https://github.com/rybalkinsd/kohttp/pull/207).
