### ISSUE TITLE
@DslMarker for narrowing the scope

### ISSUE THREAD

**Issue by DeviantBadge** [rybalkinsd/kohttp#24]
When we create new, for example, httPost we still access the receivers of the outer lambdas:
``` kotlin
httpPost {
    host = "1234"
    port = 3333
    path = "/chat/login"
    body {
        form {
            "name" to "33333"
            host = ""
        }
    }
}
```
Property host will be equal to "" instead "1234"
It can be solved by @DslMarker annotation

**Comment by rybalkinsd** [comment]
Currently, it is an expected behaviour. Changes to this repo are coming from checked production solutions. @DslMarker is already in testing
