### ISSUE TITLE
Support adding request parameter that depends on other params

### ISSUE THREAD

**Issue by SeanCai** [rybalkinsd/kohttp#52]
![image](https://user-images.githubusercontent.com/5645909/50399226-d4f95e00-07b8-11e9-9574-d942513c299d.png)

**Comment by rybalkinsd** [comment]
Need to figure out use cases

Possible API:

    sign { params: Map<String, Any?> ->
        ...
    }

**Comment by gokulchandra** [comment]
@rybalkinsd Can you provide more details this?

What I can understand is that we need a way to access the values set in the param block from within it?

```
param {
	"a" to ""
	"b" to "b"
	"sign" to sign(params) // params should refer to the previous set values of param
}
```

**Comment by gokulchandra** [comment]
Thanks for explaining that @rybalkinsd, let me dig deeper and take a stab at it. I will keep you posted.

**Comment by rybalkinsd** [comment]
has potential relation with #64 (also interceptor)
