### ISSUE TITLE
Test body content type

### ISSUE THREAD

**Issue by rybalkinsd** [rybalkinsd/kohttp#62]
Release 0.7.0 brings multiple ways to provide body content type:
1. `header { type }`
1. `body(type) { }`
1. `body { form { } / json { } }`

Todo
1. Need to update tests to check request content type
1. Need a remark in docs for cases when content type is declared with override:
```kotlin
httpPost {
    header { type 1 }
    body(type 2) {
        form { }  // <-- type 3
    }
}
```

Related to #17 #59

**Comment by mlevesquedion** [comment]
I'm gonna take a crack at this.

**Comment by mlevesquedion** [comment]
Work in progress here : #63

**Comment by rybalkinsd** [comment]
Hey, @mlevesquedion is there any update about this issue so far?

**Comment by mlevesquedion** [comment]
Hey there! I don't know when I'll have time to work on this again. I'm in school right now and I don't have much time to give.
