### ISSUE TITLE
Passing a URL instead of URL components

### ISSUE THREAD

**Issue by debuglevel** [rybalkinsd/kohttp#77]
I've got an URL `https://domain:4567/path` passed to a function, and I want to `GET` this URL with a certain header set (or a cookie, or a body when POSTing, et cetera):

```
fun download(url: String)
{
  val (myScheme, myHost, myPort, MyPath) = splitMyUrlSomehow(url)

  val response: Response = httpGet {
      scheme = myScheme
      host = myHost
      port = myPort
      path = myPath

      header {
          "some-header" to "hello there"
      }
  }
}
```

As far as I've figured out, there is no `url` var which could be used to just pass a URL. And splitting up my URL to pass its components to `httpGet` in 4 assignments seems rather cumbersome to me. Did I overlook something?

**Comment by rybalkinsd** [comment]
Hi @debuglevel .
url passing is not implemented at the moment.

For string extension (`String.httpGet`) cookie/header params are not implemented not to abuse syntax simplicity.

For `httpGet { }` method  it's possible, but need some research. 

Previously I was thinking about implementing URL and URI extension functions with an option to add cookie/header. 

If you're interested in adding this function - we can convert this issue into design proposal. Contribution is always welcome :)
