### ISSUE TITLE
compile is deprecated

### ISSUE THREAD

**Issue by pboschma** [rybalkinsd/kohttp#78]
> `Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`

The configuration for Gradle throws this. The Documentation is unclear on how to install it and where to add the lines in the `build.gradle` file.

**Comment by BoxResin** [comment]
Replace `compile` to `implementation`.
I think the README should be updated.

**Comment by rybalkinsd** [comment]
Yeah, you’re absolutely right. Inside gradle build we already moved to newer declarations: api/implementation. Now thanks to your PR our docs at up to date

**Comment by pboschma** [comment]
Maybe I am just doing this wrong, but the new installation returns the following error.

`Cannot set the value of read-only property 'name' for project ':app' of type org.gradle.api.Project.`

**Comment by rybalkinsd** [comment]
@pboschma I can have a look. Could you please provide a link to your project with this problem?

**Comment by rybalkinsd** [comment]
Feel free to reopen if problem was not fixed
